### ISSUE TITLE
Implement card swiping using something like https://github.com/gajus/swing

### ISSUE THREAD

**Issue by Pjaerr** [Pjaerr/Findr#6]
All the functionality could stay the same, just allow for card swiping and better animations using something like Swing. (https://github.com/gajus/swing)

**Comment by dylanalvarez1** [comment]
I'll try and get the swipe to work

**Comment by Pjaerr** [comment]
> I'll try and get the swipe to work

Did you make any progress on this? I looked over my code again for this app and it isn't the cleanest as I had used it to learn React. Would be happy to note any pain points as I might remake this in the future.

**Comment by Pjaerr** [comment]
Hey @dylanalvarez1 I am currently slowly rebuilding this web app as I now know way more about react. (Feel free to contribute btw)

In the rebuild I have implemented card swiping using react-swipy if you were interested in _how_ it could be done.

Here's a link to the file[s] that use it: https://github.com/Pjaerr/Findr/blob/b360994c70766d6a1678622791a1a39021038416/src/components/CardContainer/CardContainer.js
